# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- job: Linux
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.jsss'

  - script: |
      npm install
      pwd
      ls -lha
      sed -i 's/DB_HOST/spasov-db.mysql.database.azure.com/g' config/db.credentials.js
      sed -i 's/DB_USER/devops/g' config/db.credentials.js
      sed -i 's/DB_PASS/Kavadarka2006#/g' config/db.credentials.js
      sed -i 's/DB_DATABASE/spasov-db/g' config/db.credentials.js